[project]
name = "jiuhuang-pysdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "duckdb>=1.4.4",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "rich>=14.3.2",
]
